### ISSUE TITLE
Error encountered when exceeding page count

### ISSUE THREAD

**Issue by LaurenceMolloy** [LaurenceMolloy/RepoDash#10]
**Command Line Invocation:**
python3 RepoDash.py -u matplotlib -r matplotlib -m 6 -c 4 -f 159 -t issue 

[GithubIssues.py : get_next_page : 169] INFO processing page 159 of [unknown] pages...
[GithubIssues.py : get_next_page : 174] INFO remaining API call allowance = 4995.
[GithubIssues.py : get_next_page : 169] INFO processing page 160 of 161 pages...
[GithubIssues.py : get_next_page : 174] INFO remaining API call allowance = 4994.
[GithubIssues.py : get_next_page : 169] INFO processing page 161 of 161 pages...
[GithubIssues.py : get_next_page : 174] INFO remaining API call allowance = 4993.

Traceback (most recent call last):
  File "RepoDash.py", line 37, in <module>
    ga.get_next_page(args)
  File "/home/pi/Desktop/LAURENCE/GITHUB/RepoDash/src/GithubIssues.py", line 182, in get_next_page
    [self.__next_page_url] = re.findall("<([^<]*)>;\s+rel=.next",         self.__response.headers['Link'])
ValueError: not enough values to unpack (expected 1, got 0)

**Comment by LaurenceMolloy** [comment]
This simply needs a check that first page + page count - 1 <= total pages.

NOTE: we only know the total page count after the first page has been requested, so that is where we should check, reduce the page count to avoid overrunning the last page, and warn the user that we have made that adjustment. A test should be written to confirm the correct operation under these conditions.

**Comment by LaurenceMolloy** [comment]
Now resolved. See above referenced commit.
