### ISSUE TITLE
Github Enterprise

### ISSUE THREAD

**Issue by ajb1967** [LaurenceMolloy/RepoDash#30]
Hi Laurence, would it be possible for me to point your RepoDash at my github Enterprise Account (github.dxc.com) ?

What changes would I need to make ?

just change GithubIssues.py ?

Thanks,
Andy

**Comment by ajb1967** [comment]
I changed GithubIssues.py to use the Enterprise API as follows
```python
        if page_type == "issues":
            page = (args['first_page'] if 'first_page' in args else self.__utils.args['first_page'])
            self.__next_page_url = f"https://github.dxc.com/api/v3/repos/{account}/{repo}/issues?state=all&direction=asc&per_page=100&page={page}"
        elif page_type == "labels":
            page = 1
            self.__next_page_url = f"https://github.dxc.com/api/v3/repos/{account}/{repo}/labels?page={page}"    
        self.__next_page = page
```

I then ran RepoDash. It seemed to authenticate ok but got error

```bash
Andrews-MacBook-Pro:src ajb1967$ python3 RepoDash.py --authtoken xxxxxxxxxxxxxxxx --user BPSCloudOps --repo Servicedesk --months 2
/Users/ajb1967/git/bps/RepoDash/src/GithubIssues.py:90: FutureWarning: The pandas.datetime class is deprecated and will be removed from pandas in a future version. Import from datetime module instead.
  arg_parser.add_argument('-d', '--refdate', type=pd.Timestamp, default=pd.datetime.now(),
[GithubIssues.py : drop_table : 387] INFO dropping 'issues' table...
[GithubIssues.py : drop_table : 387] INFO dropping 'issue_labels' table...
[GithubIssues.py : get_next_page : 267] INFO processing page 1 of [unknown] pages...
[GithubIssues.py : get_next_page : 272] INFO remaining API call allowance = 9998.
/Users/ajb1967/git/bps/RepoDash/src/GithubIssues.py:487: FutureWarning: pandas.io.json.json_normalize is deprecated, use pandas.json_normalize instead
  df = json_normalize(label)
[GithubIssues.py : get_next_page : 267] INFO processing page 2 of 3 pages...
[GithubIssues.py : get_next_page : 272] INFO remaining API call allowance = 9997.
[GithubIssues.py : get_next_page : 267] INFO processing page 3 of 3 pages...
[GithubIssues.py : get_next_page : 272] INFO remaining API call allowance = 9996.
[GithubIssues.py : get_next_page : 287] WARN reached last page of the issues list.
[GithubIssues.py : get_next_page : 267] INFO processing page 1 of [unknown] pages...
[GithubIssues.py : get_next_page : 272] INFO remaining API call allowance = 9995.
/Users/ajb1967/git/bps/RepoDash/src/GithubIssues.py:515: FutureWarning: pandas.io.json.json_normalize is deprecated, use pandas.json_normalize instead
  df = json_normalize(issue)
[GithubIssues.py : get_next_page : 267] INFO processing page 2 of 9 pages...
[GithubIssues.py : get_next_page : 272] INFO remaining API call allowance = 9994.
[GithubIssues.py : get_next_page : 267] INFO processing page 3 of 9 pages...
[GithubIssues.py : get_next_page : 272] INFO remaining API call allowance = 9993.
[GithubIssues.py : get_next_page : 267] INFO processing page 4 of 9 pages...
[GithubIssues.py : get_next_page : 272] INFO remaining API call allowance = 9992.
[GithubIssues.py : get_next_page : 267] INFO processing page 5 of 9 pages...
[GithubIssues.py : get_next_page : 272] INFO remaining API call allowance = 9991.
[GithubIssues.py : get_next_page : 267] INFO processing page 6 of 9 pages...
[GithubIssues.py : get_next_page : 272] INFO remaining API call allowance = 9990.
[GithubIssues.py : get_next_page : 267] INFO processing page 7 of 9 pages...
[GithubIssues.py : get_next_page : 272] INFO remaining API call allowance = 9989.
[GithubIssues.py : get_next_page : 267] INFO processing page 8 of 9 pages...
[GithubIssues.py : get_next_page : 272] INFO remaining API call allowance = 9988.
[GithubIssues.py : get_next_page : 267] INFO processing page 9 of 9 pages...
[GithubIssues.py : get_next_page : 272] INFO remaining API call allowance = 9987.
[GithubIssues.py : get_next_page : 287] WARN reached last page of the issues list.
[GithubIssues.py : __get_monthly_span : 903] INFO data span is start=2019-10-04 , end=2020-12-03
INFO Processing data...
[GithubIssues.py : set_plot_window : 1095] INFO setting first plot month to Nov-20
Traceback (most recent call last):
  File "RepoDash.py", line 562, in <module>
    borderpad=0)
  File "/Users/ajb1967/.pyenv/versions/3.7.3/lib/python3.7/site-packages/mpl_toolkits/axes_grid1/inset_locator.py", line 469, in inset_axes
    inset_axes = axes_class(parent_axes.figure, parent_axes.get_position())
  File "/Users/ajb1967/.pyenv/versions/3.7.3/lib/python3.7/site-packages/mpl_toolkits/axes_grid1/parasite_axes.py", line 204, in __init__
    super().__init__(*args, **kwargs)
  File "/Users/ajb1967/.pyenv/versions/3.7.3/lib/python3.7/site-packages/matplotlib/axes/_base.py", line 496, in __init__
    self.set_figure(fig)
  File "/Users/ajb1967/.pyenv/versions/3.7.3/lib/python3.7/site-packages/matplotlib/axes/_base.py", line 626, in set_figure
    fig.transFigure)
AttributeError: 'NoneType' object has no attribute 'transFigure'
```

**Comment by LaurenceMolloy** [comment]
Hi Andy

It looks like an edge case bug that I'll need to iron out. That problem may
vanish once you have 2 or more complete calendar months to plot (in your
case, after from 01 January 2021).

In the meantime I'll take a look at this and see what needs to change to
fix it and I'll also add an option to set the API endpoint in a command
line option so the same code can be made to work with both public and
enterprise github accounts. Thanks for trying the change and demonstrating
that it works.

I'll need to replicate this scenario with something publicly accessible to
help with that.

Laurence

**Comment by ajb1967** [comment]
Thx @LaurenceMolloy, having the enterprise option will be great. 
My Servicedesk repo goes back quite some time so i tried using default of 12 months, but got the same error.
if you need me to do any testing against Github Enterprise, let me know.
Cheers,
Andy

**Comment by LaurenceMolloy** [comment]
Useful to know, thanks. Looking at my code ATM.

To confirm the situation, can I see the portion of the logging output that
shows the date range identified and first month set? It should look
something like this:

[GithubIssues.py : __get_monthly_span : 903] INFO data span is
start=2019-10-04 , end=2020-12-03
INFO Processing data...
[GithubIssues.py : set_plot_window : 1095] INFO setting first plot
month to Nov-20


Thanks

**Comment by ajb1967** [comment]
here ya go ...

```bash
Andrews-MacBook-Pro:src ajb1967$ python3 RepoDash.py --authtoken axxxxxxxxxxxxxxxxxxxxxxxxxx17 --user BPSCloudOps --repo Servicedesk
/Users/ajb1967/git/bps/RepoDash/src/GithubIssues.py:90: FutureWarning: The pandas.datetime class is deprecated and will be removed from pandas in a future version. Import from datetime module instead.
  arg_parser.add_argument('-d', '--refdate', type=pd.Timestamp, default=pd.datetime.now(),
[GithubIssues.py : drop_table : 387] INFO dropping 'issues' table...
[GithubIssues.py : drop_table : 387] INFO dropping 'issue_labels' table...
[GithubIssues.py : get_next_page : 267] INFO processing page 1 of [unknown] pages...
[GithubIssues.py : get_next_page : 272] INFO remaining API call allowance = 9986.
/Users/ajb1967/git/bps/RepoDash/src/GithubIssues.py:487: FutureWarning: pandas.io.json.json_normalize is deprecated, use pandas.json_normalize instead
  df = json_normalize(label)
[GithubIssues.py : get_next_page : 267] INFO processing page 2 of 3 pages...
[GithubIssues.py : get_next_page : 272] INFO remaining API call allowance = 9985.
[GithubIssues.py : get_next_page : 267] INFO processing page 3 of 3 pages...
[GithubIssues.py : get_next_page : 272] INFO remaining API call allowance = 9984.
[GithubIssues.py : get_next_page : 287] WARN reached last page of the issues list.
[GithubIssues.py : get_next_page : 267] INFO processing page 1 of [unknown] pages...
[GithubIssues.py : get_next_page : 272] INFO remaining API call allowance = 9983.
/Users/ajb1967/git/bps/RepoDash/src/GithubIssues.py:515: FutureWarning: pandas.io.json.json_normalize is deprecated, use pandas.json_normalize instead
  df = json_normalize(issue)
[GithubIssues.py : get_next_page : 267] INFO processing page 2 of 9 pages...
[GithubIssues.py : get_next_page : 272] INFO remaining API call allowance = 9982.
[GithubIssues.py : get_next_page : 267] INFO processing page 3 of 9 pages...
[GithubIssues.py : get_next_page : 272] INFO remaining API call allowance = 9981.
[GithubIssues.py : get_next_page : 267] INFO processing page 4 of 9 pages...
[GithubIssues.py : get_next_page : 272] INFO remaining API call allowance = 9980.
[GithubIssues.py : get_next_page : 267] INFO processing page 5 of 9 pages...
[GithubIssues.py : get_next_page : 272] INFO remaining API call allowance = 9979.
[GithubIssues.py : get_next_page : 267] INFO processing page 6 of 9 pages...
[GithubIssues.py : get_next_page : 272] INFO remaining API call allowance = 9978.
[GithubIssues.py : get_next_page : 267] INFO processing page 7 of 9 pages...
[GithubIssues.py : get_next_page : 272] INFO remaining API call allowance = 9977.
[GithubIssues.py : get_next_page : 267] INFO processing page 8 of 9 pages...
[GithubIssues.py : get_next_page : 272] INFO remaining API call allowance = 9976.
[GithubIssues.py : get_next_page : 267] INFO processing page 9 of 9 pages...
[GithubIssues.py : get_next_page : 272] INFO remaining API call allowance = 9975.
[GithubIssues.py : get_next_page : 287] WARN reached last page of the issues list.
[GithubIssues.py : __get_monthly_span : 903] INFO data span is start=2019-10-04 , end=2020-12-03
INFO Processing data...
[GithubIssues.py : set_plot_window : 1095] INFO setting first plot month to Jan-20
Traceback (most recent call last):
  File "RepoDash.py", line 562, in <module>
    borderpad=0)
  File "/Users/ajb1967/.pyenv/versions/3.7.3/lib/python3.7/site-packages/mpl_toolkits/axes_grid1/inset_locator.py", line 469, in inset_axes
    inset_axes = axes_class(parent_axes.figure, parent_axes.get_position())
  File "/Users/ajb1967/.pyenv/versions/3.7.3/lib/python3.7/site-packages/mpl_toolkits/axes_grid1/parasite_axes.py", line 204, in __init__
    super().__init__(*args, **kwargs)
  File "/Users/ajb1967/.pyenv/versions/3.7.3/lib/python3.7/site-packages/matplotlib/axes/_base.py", line 496, in __init__
    self.set_figure(fig)
  File "/Users/ajb1967/.pyenv/versions/3.7.3/lib/python3.7/site-packages/matplotlib/axes/_base.py", line 626, in set_figure
    fig.transFigure)
AttributeError: 'NoneType' object has no attribute 'transFigure'
```

**Comment by LaurenceMolloy** [comment]
I can confirm that the code is broken for me also on examples that should
ordinarily work. I see that there are deprecation warnings. Let me address
those first and see if that fixes things before we delve any deeper.

**Comment by ajb1967** [comment]
ok thanks @LaurenceMolloy will wait for an update.
regards,
Andy

**Comment by LaurenceMolloy** [comment]
Commit 4d4cf6ab1ca279cf7d51abe7d3ad3d8dc4d3a8c5 (latest master branch) should address the error you encountered and remove the observable deprecation errors.

This version also allows you to use the same codebase for both public Github and Github Enterprise. For your particular use case you will need to add the following extra arguments to your command line.

    -fqdn github.dxc.com -https

I've presumed that the "/api/v3" is a fixed addition to the URL for all Enterprise installations (relative to public Github) - can you let me know if it isn't.

I shall leave this issue open until I hear confirmation from you that it works for you.

Thanks
Laurence

**Comment by ajb1967** [comment]
Hi Laurence,

worked like a charm. Thank you.

According to [Github Enterprise documentation:](https://developer.github.com/enterprise/2.21/v3/enterprise-admin/)

```text
REST API endpoints—except Management Console API endpoints—are prefixed with the following URL:

http(s)://hostname/api/v3/
```

```bash
$ python3 RepoDash.py --authtoken a38n --user BPSCloudOps --repo Servicedesk --months 12 -fqdn github.dxc.com -https
```

![Screenshot 2020-12-04 at 08 27 23](https://user-images.githubusercontent.com/34161302/101140537-03ba1900-360b-11eb-8c1b-0a77cd6b74b4.png)

is i possible to get metrics in csv format to download ?

Thanks,
Andy

**Comment by LaurenceMolloy** [comment]
Thanks for confirming. I'll close the ticket.

I love that peak in the months immediately following the first lockdown.
That's something quite illuminating.

CSV: pop a wee feature request into the issues list... you never know! ;)

Laurence

**Comment by LaurenceMolloy** [comment]
BTW... I note the highlighted label in the panel on the left - that makes me think that you obtained that image by taking a screenshot. You can also generate a png image file from the dashboard for inclusion in a report by using the -s/--savefile option.

Laurence
