### ISSUE TITLE
[BUG] Meaningless error when exhausting API call allowance

### ISSUE THREAD

**Issue by LaurenceMolloy** [LaurenceMolloy/RepoDash#31]
**DESCRIPTION**

When exhausting your API call allowance the error below is output. This error is meaningless in this situation. It would be better to catch this condition, report it and exit.

**ERROR MESSAGE**

[GithubIssues.py : get_next_page : 268] INFO processing page 170 of [unknown] pages...
[GithubIssues.py : get_next_page : 273] INFO remaining API call allowance = 0.
[GithubIssues.py : get_next_page : 268] INFO processing page 171 of 179 pages...
[GithubIssues.py : get_next_page : 273] INFO remaining API call allowance = 0.
Traceback (most recent call last):
  File "RepoDash.py", line 74, in <module>
    ga.get_next_page(args)
  File "/home/pi/Desktop/LAURENCE/GITHUB/RepoDash/src/GithubIssues.py", line 276, in get_next_page
    if not self.__response.headers['Status'].startswith("200 "):
  File "/usr/lib/python3/dist-packages/requests/structures.py", line 52, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'status'

**REPRODUCING THIS ERROR**

Simply run RepoDash on any repository larger than 60 pages, requesting at least 60 pages (-c argument), without using an auth token to exhaust your hourly API call allowance. 

e.g. RepoDash.py -u numpy -r numpy -c 60

**Comment by LaurenceMolloy** [comment]
Fixed with the requests module exception handling that has been added to the get_next_page() function.

Commit 4d4cf6ab1ca279cf7d51abe7d3ad3d8dc4d3a8c5 closes #31
