### ISSUE TITLE
Error encountered when running against this repository

### ISSUE THREAD

**Issue by LaurenceMolloy** [LaurenceMolloy/RepoDash#5]
Command line invocation:

python3 RepoDash.py -u laurencemolloy -r RepoDash

Error Encountered:

Traceback (most recent call last):
  File "RepoDash.py", line 54, in <module>
    ga.get_next_page()
  File "/home/pi/Desktop/LAURENCE/GITHUB/RepoDash/src/GithubIssues.py", line 90, in get_next_page
    [self.__next_page_url] = re.findall("<([^<]*)>;\s+rel=.next",         self.__response.headers['Link'])
  File "/usr/lib/python3/dist-packages/requests/structures.py", line 52, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'link'

**Comment by LaurenceMolloy** [comment]
This issue arises because there is only one page of issues. The "Link" field (containing previous, next and last page links) is absent from the headers returned by GitHub API yet the code presumes it to exist.

This condition needs to be captured and handled properly and a test written against this bug.

**Comment by LaurenceMolloy** [comment]
Current version of RepoDash now errors in this way...

`
File "src/RepoDash.py", line 44, in <module>
    ga.get_next_page(args)
  File "/home/pi/Desktop/LAURENCE/GITHUB/RepoDash/src/GithubIssues.py", line 260, in get_next_page
    [self.__next_page_url] = re.findall("<([^<]*)>;\s+rel=.next",         self.__response.headers['Link'])
ValueError: not enough values to unpack (expected 1, got 0)
`
