### ISSUE TITLE
ValueError encountered (X must have 2 or fewer dimensions)

### ISSUE THREAD

**Issue by LaurenceMolloy** [LaurenceMolloy/RepoDash#7]
**Intention:**
For the Kubernetes repo, starting from issues page 200, collate stats for 7 pages and attempt to display 12 months of metrics history (stretching back from latest month of data collected)

**Command Line Invocation:**
python3 RepoDash.py -u kubernetes -r kubernetes -m 12  -c 7 -f 200

**Error Response:**
`
Traceback (most recent call last):
  File "RepoDash.py", line 282, in <module>
    plt.boxplot(ages[1:], widths=0.5, positions=positions[1:], patch_artist=True)
  File "/home/pi/.local/lib/python3.7/site-packages/matplotlib/pyplot.py", line 2473, in boxplot
    is not None else {}))
  File "/home/pi/.local/lib/python3.7/site-packages/matplotlib/cbook/deprecation.py", line 307, in wrapper
    return func(*args, **kwargs)
  File "/home/pi/.local/lib/python3.7/site-packages/matplotlib/__init__.py", line 1599, in inner
    return func(ax, *map(sanitize_sequence, args), **kwargs)
  File "/home/pi/.local/lib/python3.7/site-packages/matplotlib/axes/_axes.py", line 3669, in boxplot
    labels=labels, autorange=autorange)
  File "/home/pi/.local/lib/python3.7/site-packages/matplotlib/cbook/__init__.py", line 1245, in boxplot_stats
    X = _reshape_2D(X, "X")
  File "/home/pi/.local/lib/python3.7/site-packages/matplotlib/cbook/__init__.py", line 1436, in _reshape_2D
    raise ValueError("{} must have 2 or fewer dimensions".format(name))
ValueError: X must have 2 or fewer dimensions
`

**Comment by LaurenceMolloy** [comment]
Cannot reproduce this since latest commit. Error now manifests as follows:

`
Traceback (most recent call last):
  File "RepoDash.py", line 39, in <module>
    ga.get_next_page()
  File "/home/pi/Desktop/LAURENCE/GITHUB/RepoDash/src/GithubIssues.py", line 172, in get_next_page
    [self.__next_page_url] = re.findall("<([^<]*)>;\s+rel=.next",         self.__response.headers['Link'])
ValueError: not enough values to unpack (expected 1, got 0)
`

Re-running this from page 100 results in matplotlib output

**Command Line Invocation:**
python3 RepoDash.py -u kubernetes -r kubernetes -m 12 -c 7 -f 100

 Log messages from above invocation suggest that the number of issues pages is now only 152 (previously expected 867), so page number requested exceeds total pages - a new type of error to capture and test for.

**Comment by LaurenceMolloy** [comment]
I can replicate this with the following invocation:
python3 RepoDash.py -u matplotlib -r matplotlib -m 6 -c 5 -f 157 -t issue

**Comment by LaurenceMolloy** [comment]
Fixed.

In RepoDash.py change
`
npa = db.get_issue_ages(args['issue_type'], idx.strftime('%Y-%m-%d'))
gd.issue_ages.append(npa.values)
`
to
`
npa = db.get_issue_ages(args['issue_type'], idx.strftime('%Y-%m-%d'))
gd.issue_ages.append(npa.values.flatten())
`

 Both examples above now generate a plot. Above code change will be committed shortly.
